stages:
  - build-frontend-customer
  - build-frontend-restaurant
  - deploy

build-frontend-customer:
  stage: build-frontend-customer
  script:
    - source ~/.bashrc
    - export PATH=$PATH:/home/gitlab-runner/.nvm/versions/node/v12.17.0/bin
    - echo $PATH
    - cd frontend-customer
    - npm install
    - expo publish
    - turtle build:android \--keystore-path ~/keys/parallelq.jks \--keystore-alias QGFva2lzZWl5YS9wYXJhbGxlbHE= -t apk -o ~/output/parallelq.apk > ~/logs/customer_build_log 2>&1
    - cd ..

build-frontend-restaurant:
  stage: build-frontend-restaurant
  script:
    - source ~/.bashrc
    - export PATH=$PATH:/home/gitlab-runner/.nvm/versions/node/v12.17.0/bin
    - echo $PATH
    - cd frontend-restaurant
    - npm install
    - expo publish
    - turtle build:android \--keystore-path ~/keys/parallelq.jks \--keystore-alias QGFva2lzZWl5YS9wYXJhbGxlbHE= -t apk -o ~/output/parallelq-restaurant.apk > ~/logs/restaurant_build_log 2>&1
    - cd ..

deploy:
  stage: deploy
  script:
    - cp ~/output/parallelq.apk ~/frontend-deploy/parallelq.apk
    - cp ~/output/parallelq-restaurant.apk ~/frontend-deploy/parallelq-restaurant.apk
    - pushd ~/frontend-deploy
    - git add *
    - git commit -am "Automatic apk deployment" || true
    - git push heroku master || true
    - popd
    - cp -TR backend ~/backend-deploy
    - pushd ~/backend-deploy
    - git add *
    - git commit -am "Automatic backend deployment" || true
    - git push heroku master
