stages:
  - build-frontend-customer
  - deploy

build-frontend-customer:
  stage: build-frontend-customer
  script:
    - source ~/.bashrc
    - export PATH=$PATH:/home/gitlab-runner/.nvm/versions/node/v12.17.0/bin
    - echo $PATH
    - cd frontend-customer
    - npm install
    - expo publish
    - turtle build:android \--keystore-path ~/keys/parallelq.jks \--keystore-alias QGFva2lzZWl5YS9wYXJhbGxlbHE= -t apk -o ~/output/parallelq.apk > ~/logs/buildlog 2>&1
    - cd ..


deploy:
  stage: deploy
  script:
    - pushd frontend-customer
    - cp ~/output/parallelq.apk ~/frontend-deploy/parallelq.apk
    - cd ~/frontend-deploy
    - git add *
    - git commit -am "Automatic apk deployment"
    - git push heroku master
    - popd
    - cp -TR /backend ~/backend-deploy
    - cd ~/backend-deploy
    - git add *
    - git commit -am "Automatic apk deployment"
    - git push heroku master
