stages:
  - build
  - deploy

build:
  stage: build
  script:
    - source ~/.bashrc
    - export PATH=$PATH:/home/cya/.nvm/versions/node/v12.17.0/bin
    - echo $PATH
    - cd frontend-customer
    - npm install
    - turtle build:android \--keystore-path ~/Projects/DRP/androidkey/parallelq.jks \--keystore-alias QGFva2lzZWl5YS9wYXJhbGxlbHE= -t apk -o ./output.apk > ~/gitlabrunner/logs/buildlog 2>&1
    - cp output.apk ~/gitlabrunner/output/parallelq.apk
    - cd ..


deploy:
  stage: deploy
  script:
    - cd frontend-customer
    - git clone --single-branch --branch initial git@gitlab.doc.ic.ac.uk:g1927138/parallelq-deploy.git
    - cd parallelq-deploy
    - cp ~/gitlabrunner/output/parallelq.apk public/parallelq.apk
    - git checkout -b master
    - git add *
    - git commit -am "Automatic apk deployment"
    - git push origin master --force
    - cd ../..
