stages:
  - build
  - deploy

build:
  stage: build
  script:
    - source ~/.bashrc
    - export PATH=$PATH:/home/cya/.nvm/versions/node/v12.17.0/bin
    - echo $PATH
    - cd frontend-customer
    - npm install
    - expo publish
    - turtle build:android \--keystore-path ~/Projects/DRP/androidkey/parallelq.jks \--keystore-alias QGFva2lzZWl5YS9wYXJhbGxlbHE= -t apk -o ./output.apk > ~/gitlabrunner/logs/buildlog 2>&1
    - cp output.apk ~/gitlabrunner/output/parallelq.apk
    - cd ..


deploy:
  stage: deploy
  script:
    - cd frontend-customer
    - rm ~/gitlabrunner/drp-parallelq/parallelq.apk
    - cp ~/gitlabrunner/output/parallelq.apk ~/gitlabrunner/drp-parallelq/parallelq.apk
    - cd ~/gitlabrunner/drp-parallelq/
    - git add *
    - git commit -am "Automatic apk deployment"
    - git push heroku master